export enum Permission {
  SEND_MESSAGES = 'SEND_MESSAGES',
  REACT_TO_MESSAGES = 'REACT_TO_MESSAGES',
  PIN_MESSAGES = 'PIN_MESSAGES',
  UPLOAD_FILES = 'UPLOAD_FILES',
  JOIN_VOICE_CHANNELS = 'JOIN_VOICE_CHANNELS',
  SHARE_SCREEN = 'SHARE_SCREEN',
  ENABLE_WEBCAM = 'ENABLE_WEBCAM',
  // ADMIN PERMISSIONS
  MANAGE_CHANNELS = 'MANAGE_CHANNELS',
  MANAGE_CHANNEL_PERMISSIONS = 'MANAGE_CHANNEL_PERMISSIONS',
  MANAGE_CATEGORIES = 'MANAGE_CATEGORIES',
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_EMOJIS = 'MANAGE_EMOJIS',
  MANAGE_SETTINGS = 'MANAGE_SETTINGS',
  MANAGE_USERS = 'MANAGE_USERS',
  KICK_MEMBERS = 'KICK_MEMBERS',
  BAN_MEMBERS = 'BAN_MEMBERS',
  MUTE_MEMBERS = 'MUTE_MEMBERS',
  DEAFEN_MEMBERS = 'DEAFEN_MEMBERS',
  DELETE_USERS = 'DELETE_USERS',
  VIEW_AUDIT_LOG = 'VIEW_AUDIT_LOG',
  MOVE_MEMBERS = 'MOVE_MEMBERS',
  MENTION_EVERYONE = 'MENTION_EVERYONE',
  CHANGE_NICKNAME = 'CHANGE_NICKNAME',
  MANAGE_NICKNAMES = 'MANAGE_NICKNAMES',
  EMBED_LINKS = 'EMBED_LINKS',
  MANAGE_MESSAGES = 'MANAGE_MESSAGES',
  MANAGE_STORAGE = 'MANAGE_STORAGE',
  MANAGE_INVITES = 'MANAGE_INVITES',
  MANAGE_UPDATES = 'MANAGE_UPDATES',
  MANAGE_PLUGINS = 'MANAGE_PLUGINS',
  USE_PLUGINS = 'USE_PLUGINS',
  VIEW_USER_SENSITIVE_DATA = 'VIEW_USER_SENSITIVE_DATA',
  SET_VOICE_CHANNEL_STATUS = 'SET_VOICE_CHANNEL_STATUS'
}

export const DEFAULT_ROLE_PERMISSIONS = [
  Permission.JOIN_VOICE_CHANNELS,
  Permission.SEND_MESSAGES,
  Permission.UPLOAD_FILES,
  Permission.SHARE_SCREEN,
  Permission.ENABLE_WEBCAM,
  Permission.CHANGE_NICKNAME,
  Permission.EMBED_LINKS
];

export const USER_MODERATION_PERMISSIONS: Permission[] = [
  Permission.MANAGE_USERS,
  Permission.KICK_MEMBERS,
  Permission.BAN_MEMBERS,
  Permission.DELETE_USERS
];

export const USER_ADMIN_VIEW_PERMISSIONS: Permission[] = [
  ...USER_MODERATION_PERMISSIONS,
  Permission.VIEW_AUDIT_LOG
];

export enum UploadHeaders {
  ORIGINAL_NAME = 'x-file-name',
  TYPE = 'x-file-type',
  CONTENT_LENGTH = 'content-length',
  TOKEN = 'x-token'
}

export enum ChannelPermission {
  VIEW_CHANNEL = 'VIEW_CHANNEL',
  SEND_MESSAGES = 'SEND_MESSAGES',
  JOIN = 'JOIN',
  SPEAK = 'SPEAK',
  SHARE_SCREEN = 'SHARE_SCREEN',
  WEBCAM = 'WEBCAM'
}
